file_format: "1"
id: lily58
name: Lily58
type: shield
url: https://github.com/nstauder2/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - lily58_left
  - lily58_right